### PR TITLE
Added update_cards api call

### PR DESCRIPTION
**Pull request by aig787**

### CODE REVIEW

**Comment by bethanylong** [comment]
Couple minor things:
- Does "mult" stand for "multiplicity"? If so, might want to make that slightly more explicit.
- Typo on first line of docstring: matchint -> matching

**Comment by aig787** [comment]
For the first one I wanted to know what you guys thought about that. I agree something more explicit would be nice, I was just matching the pymongo syntax for the call more or less.

**Comment by bethanylong** [comment]
I really like being able to choose whether multiple (and I think "multiple" is actually the right full word) records are updated. If you fix the typo and change "mult" to "multiple", I'd be glad to merge this.

**Comment by aig787** [comment]
Fixed

**Comment by bethanylong** [comment]
And also in the docstring? :)

**Pull request merged**
